# MySQL Configuration
# Make sure the values are the exact same
# as in your CoreProtect config.
# By default table prefix is co_
mysql-host: "host-name"
mysql-port: 3306
mysql-database: "database-name"
mysql-username: "database-user"
# Leave '' if password not required
mysql-password: "user-password"

# Discord BOT Token
# https://discord.com/developers/applications
discord-bot-token: "your-token"
command-prefix: "co!"

# Role IDs that are allowed to use the commands
# You have to have developer mode enabled on discord
# and then you can right click on a role name and copy its ID.
allowed-roles:
  - 'role-one-id'
  - 'role-two-id'