name: M0-CoreCord
main: me.m0dii.corecord.CoreCord
description: Discord integration for CoreProtect.
version: 1.8.0
api-version: 1.13
author: M0dii
depend: [CoreProtect]
softdepend: [PlaceholderAPI]
permissions:
  corecord.update.notify:
    description: Notifies users with this permission when there is update.
    default: op
  corecord.main:
    description: Main command.
    default: op
  corecord.comand.reload:
    description: Reload command.
    default: op
  corecord.comand.version:
    description: Version command.
    default: op
commands:
  corecord:
    description: Main command.
    permission: corecord.main