package me.m0dii.corecord.utils;

public enum Message {
    EMBED_RESULT_COUNT,
    EMBED_NO_RESULTS,
    EMBED_NO_RESULTS_FILTER,
    EMBED_TITLE,
    GAME_CONFIG_RELOAD,
    EMBED_CONFIG_RELOAD,
    EMBED_SPECIFY_TIME,
    COORDINATE_ROW
}
